### PR TITLE
observer update handlers should be non optional

### PR DESCRIPTION
**Pull request by mitulmanish**

### CODE REVIEW

**Comment by tatey** [comment]
Looks good to me. Bump? :smile:

**Comment by mitulmanish** [comment]
@tatey I have tested the branch locally , it looks good.We should merge this 👍

**Comment by tatey** [comment]
Sounds good to me. I don't have write access to this repo anymore. Do you reckon you could add these changes to https://github.com/tatey/lifxhttpkit?

**Comment by mitulmanish** [comment]
Swift 3 PR on https://github.com/tatey/lifxhttpkit is updated now.

**Pull request merged**
